### PR TITLE
[FIX #31] Subscription messages are arriving before the protocol message for the subscription.

### LINKED ISSUE #31: Subscription protocol response message can be received after a message
When I remove the first line it works.

```js
const nats = require('nats').connect()
const natsStreaming = require('node-nats-streaming').connect('test-cluster', 'test')


natsStreaming.on('connect', function () {

  natsStreaming.publish('foo', 'Hello node-nats-streaming!', function (err, aGuid) {
    console.log('Error publishing: ' + aGuid + ' - ' + err)
  })

  // Subscriber can specify how many existing messages to get.
  var opts = natsStreaming.subscriptionOptions().setStartWithLastReceived();
  var subscription = natsStreaming.subscribe('foo', opts);
  subscription.on('message', function (msg) {
    console.log('Received a message [' + msg.getSequence() + '] ' + msg.getData());
  })

})
```

**Error:**

```
E:\Repositorys\hemera>node examples\full-example.js
Received a message [9] Hello node-nats-streaming!

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error
    at Client.publish (E:\Repositorys\hemera\node_modules\nats\lib\nats.js:1019:13)
    at Message.ack (E:\Repositorys\hemera\node_modules\node-nats-streaming\lib\stan.js:748:24)
    at Message.maybeAutoAck (E:\Repositorys\hemera\node_modules\node-nats-streaming\lib\stan.js:735:10)
    at Object.callback (E:\Repositorys\hemera\node_modules\node-nats-streaming\lib\stan.js:634:11)
    at Client.processMsg (E:\Repositorys\hemera\node_modules\nats\lib\nats.js:954:11)
    at Client.processInbound (E:\Repositorys\hemera\node_modules\nats\lib\nats.js:882:14)
    at Socket.<anonymous> (E:\Repositorys\hemera\node_modules\nats\lib\nats.js:465:12)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
```

### PR DESCRIPTION
**Pull request by aricart**
@kozlovic This solves the issue by deferring message processing until the protocol message has been received.

### CODE REVIEW

**Comment by kozlovic** [comment]
@aricart The server is sending the response *before* the data. Here is where it sends the response. Notice the use of `s.ncs.Publish()`:
https://github.com/nats-io/nats-streaming-server/blob/master/server/server.go#L2773

After that, it sends possible data here: https://github.com/nats-io/nats-streaming-server/blob/master/server/server.go#L2786

which ends-up invoking this: https://github.com/nats-io/nats-streaming-server/blob/master/server/server.go#L2055
Notice again the use of the same connection: `s.ncs.Publish()` to publish the data. So messages should arrive in order in the node library.

**Comment by kozlovic** [comment]
@aricart LGTM.

We found that this is likely a problem with the server, which may be challenging to address. In the meantime, this PR will prevent the issue from happening. Other nats-streaming clients are not affected due to the use of locking.

**Comment by petemiron** [comment]
@aricart please add tests to improve or stabilize coverage and get this merged.

**Comment by aricart** [comment]
The fix was implemented in the server. No change is needed in the library.

**Pull request closed without merging**
