### PR TITLE
adding catch to ack publish

### PR DESCRIPTION
**Pull request by dimiras**
The publish for the acknowledge seems to be missing a catch statement, causing an unhandled exception, possibly breaking apps that use this library. E.g an Electron App.
error

### CODE REVIEW

**Comment by aricart** [comment]
@dimiras Thanks for your report.

Can you tell me the version of Stan and NATS library you are using?

Also for your pull request, can you correct the syntax errors and remove your formatting changes so that only your proposed change is shown.

From the looks of it, it looks as if you are not providing a callback, so the exception needs to be caught by you.

**Comment by aricart** [comment]
The only reason for this to be throwing an error is that the protocol message with the subjects has not been returned. This I recall was an issue with the nats-streaming-server at some point in time.

**Comment by dimiras** [comment]
I'm using "node-nats-streaming": "0.0.41" and nats-streaming-server 0.9.2.
Ok i will try to fix the syntax and formatting problems.

Thanks

**Comment by dimiras** [comment]
Fixed my issue using Manual Ack Mode and using try catch at my side. But i still think that the auto ack mode should be resilient when this kind of errors occur.

**Comment by aricart** [comment]
@dimiras I will verify this - it sounds like a regression from the server. Is it possible for you to catch the actual error you are getting? I want to make sure this is correct.

**Pull request closed without merging**
